# Generated by Django 4.2.23 on 2025-10-16 19:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='en_geofence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='ubicacion_foto',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='visit',
            name='geofence',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
