# Generated by Django 4.2.23 on 2025-10-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0002_evidence_en_geofence_evidence_ubicacion_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
