# Generated by Django 4.2.23 on 2025-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0003_review_rechazada'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='secciones',
            field=models.ManyToManyField(blank=True, related_name='visitas', to='GeoInsightApp.section'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente Responsable'), ('admin', 'Administrador'), ('supervisor_vcm', 'Supervisor VcM'), ('apoyo', 'Docente Apoyo TI'), ('coordinador', 'Coordinador API'), ('fg', 'Formación General')], default='estudiante', max_length=20),
        ),
    ]
