# Generated by Django 4.2.23 on 2025-10-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0004_visit_secciones_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente Responsable'), ('admin', 'Administrador'), ('supervisor_vcm', 'Supervisor VcM'), ('fg', 'Formación General')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='GeoInsightApp.career'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='GeoInsightApp.section'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='GeoInsightApp.semester'),
        ),
        migrations.AlterField(
            model_name='section',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='sections', to='GeoInsightApp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='GeoInsightApp.role'),
        ),
    ]
