# Generated by Django 4.2.23 on 2025-10-28 04:37

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('GeoInsightApp', 'Role')
    roles = ['estudiante', 'docente', 'admin', 'supervisor_vcm', 'fg']
    for r in roles:
        Role.objects.get_or_create(name=r)

class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0005_role_remove_userprofile_role_userprofile_career_and_more'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
