# Generated by Django 4.2.23 on 2025-10-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0006_create_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='GeoInsightApp.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='students', to='GeoInsightApp.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='sections_as_docente', to='GeoInsightApp.userprofile'),
        ),
    ]
