# Generated by Django 4.2.23 on 2025-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0007_remove_userprofile_section_course_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='sections_as_student', to='GeoInsightApp.userprofile'),
        ),
    ]
