# Generated by Django 4.2.23 on 2025-10-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0008_remove_userprofile_sections_section_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='secciones',
        ),
        migrations.AddField(
            model_name='visit',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='GeoInsightApp.section'),
        ),
    ]
