# Generated by Django 4.2.23 on 2025-10-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0009_remove_visit_secciones_visit_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='section',
        ),
        migrations.AddField(
            model_name='visit',
            name='sections',
            field=models.ManyToManyField(related_name='visitas', to='GeoInsightApp.section'),
        ),
    ]
