# Generated by Django 4.2.23 on 2025-11-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInsightApp', '0010_remove_visit_section_visit_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
